FROM rust:1.39-alpine

ENV PROJECT_PATH=/chirpstack-api
RUN apk add --no-cache make git bash protobuf protobuf-dev

RUN git clone https://github.com/protocolbuffers/protobuf.git /protobuf
RUN git clone https://github.com/googleapis/googleapis.git /googleapis

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH
