FROM rust:1.61

ENV PROJECT_PATH=/chirpstack-api
RUN apt-get update && \
	apt-get install -y make git bash protobuf-compiler && \
	apt-get clean

RUN git clone https://github.com/googleapis/googleapis.git /googleapis


RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH
