FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

RUN apt update && apt install -y make git
RUN git clone --depth=1 --branch=master https://github.com/googleapis/googleapis.git /googleapis
RUN mkdir -p /src/protobuf/google/api
RUN cp -r /googleapis/google/api/*.proto /src/protobuf/google/api/

WORKDIR /src
COPY csharp .
COPY protobuf /src/protobuf/


#RUN dotnet restore "Chirpstack.Api.csproj"
#RUN dotnet build "Chirpstack.Api.csproj" -c Release -o /app/build