FROM maven:3.8-jdk-8

ENV PROJECT_PATH=/chirpstack-api

#RUN apt update && apt install -y make git protobuf-compiler libprotobuf-dev libprotobuf-java protobuf-compiler-grpc
RUN apt update && apt install -y make git

#detected platform from protobuf-maven-plugin
#RUN wget -t 1 -O /protoc-gen-grpc-java https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.31.0/protoc-gen-grpc-java-1.31.0-linux-x86_64.exe
#RUN chmod +x /protoc-gen-grpc-java

RUN git clone https://github.com/googleapis/googleapis.git /googleapis

RUN mkdir -p PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH
