// GENERATED CODE -- DO NOT EDIT!

// package: ns
// file: ns/ns.proto

import * as ns_ns_pb from "../ns/ns_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as grpc from "grpc";

interface INetworkServerServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  createServiceProfile: grpc.MethodDefinition<ns_ns_pb.CreateServiceProfileRequest, ns_ns_pb.CreateServiceProfileResponse>;
  getServiceProfile: grpc.MethodDefinition<ns_ns_pb.GetServiceProfileRequest, ns_ns_pb.GetServiceProfileResponse>;
  updateServiceProfile: grpc.MethodDefinition<ns_ns_pb.UpdateServiceProfileRequest, google_protobuf_empty_pb.Empty>;
  deleteServiceProfile: grpc.MethodDefinition<ns_ns_pb.DeleteServiceProfileRequest, google_protobuf_empty_pb.Empty>;
  createRoutingProfile: grpc.MethodDefinition<ns_ns_pb.CreateRoutingProfileRequest, ns_ns_pb.CreateRoutingProfileResponse>;
  getRoutingProfile: grpc.MethodDefinition<ns_ns_pb.GetRoutingProfileRequest, ns_ns_pb.GetRoutingProfileResponse>;
  updateRoutingProfile: grpc.MethodDefinition<ns_ns_pb.UpdateRoutingProfileRequest, google_protobuf_empty_pb.Empty>;
  deleteRoutingProfile: grpc.MethodDefinition<ns_ns_pb.DeleteRoutingProfileRequest, google_protobuf_empty_pb.Empty>;
  createDeviceProfile: grpc.MethodDefinition<ns_ns_pb.CreateDeviceProfileRequest, ns_ns_pb.CreateDeviceProfileResponse>;
  getDeviceProfile: grpc.MethodDefinition<ns_ns_pb.GetDeviceProfileRequest, ns_ns_pb.GetDeviceProfileResponse>;
  updateDeviceProfile: grpc.MethodDefinition<ns_ns_pb.UpdateDeviceProfileRequest, google_protobuf_empty_pb.Empty>;
  deleteDeviceProfile: grpc.MethodDefinition<ns_ns_pb.DeleteDeviceProfileRequest, google_protobuf_empty_pb.Empty>;
  createDevice: grpc.MethodDefinition<ns_ns_pb.CreateDeviceRequest, google_protobuf_empty_pb.Empty>;
  getDevice: grpc.MethodDefinition<ns_ns_pb.GetDeviceRequest, ns_ns_pb.GetDeviceResponse>;
  updateDevice: grpc.MethodDefinition<ns_ns_pb.UpdateDeviceRequest, google_protobuf_empty_pb.Empty>;
  deleteDevice: grpc.MethodDefinition<ns_ns_pb.DeleteDeviceRequest, google_protobuf_empty_pb.Empty>;
  activateDevice: grpc.MethodDefinition<ns_ns_pb.ActivateDeviceRequest, google_protobuf_empty_pb.Empty>;
  deactivateDevice: grpc.MethodDefinition<ns_ns_pb.DeactivateDeviceRequest, google_protobuf_empty_pb.Empty>;
  getDeviceActivation: grpc.MethodDefinition<ns_ns_pb.GetDeviceActivationRequest, ns_ns_pb.GetDeviceActivationResponse>;
  createDeviceQueueItem: grpc.MethodDefinition<ns_ns_pb.CreateDeviceQueueItemRequest, google_protobuf_empty_pb.Empty>;
  flushDeviceQueueForDevEUI: grpc.MethodDefinition<ns_ns_pb.FlushDeviceQueueForDevEUIRequest, google_protobuf_empty_pb.Empty>;
  getDeviceQueueItemsForDevEUI: grpc.MethodDefinition<ns_ns_pb.GetDeviceQueueItemsForDevEUIRequest, ns_ns_pb.GetDeviceQueueItemsForDevEUIResponse>;
  getNextDownlinkFCntForDevEUI: grpc.MethodDefinition<ns_ns_pb.GetNextDownlinkFCntForDevEUIRequest, ns_ns_pb.GetNextDownlinkFCntForDevEUIResponse>;
  getRandomDevAddr: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, ns_ns_pb.GetRandomDevAddrResponse>;
  createMACCommandQueueItem: grpc.MethodDefinition<ns_ns_pb.CreateMACCommandQueueItemRequest, google_protobuf_empty_pb.Empty>;
  sendProprietaryPayload: grpc.MethodDefinition<ns_ns_pb.SendProprietaryPayloadRequest, google_protobuf_empty_pb.Empty>;
  createGateway: grpc.MethodDefinition<ns_ns_pb.CreateGatewayRequest, google_protobuf_empty_pb.Empty>;
  getGateway: grpc.MethodDefinition<ns_ns_pb.GetGatewayRequest, ns_ns_pb.GetGatewayResponse>;
  updateGateway: grpc.MethodDefinition<ns_ns_pb.UpdateGatewayRequest, google_protobuf_empty_pb.Empty>;
  deleteGateway: grpc.MethodDefinition<ns_ns_pb.DeleteGatewayRequest, google_protobuf_empty_pb.Empty>;
  generateGatewayClientCertificate: grpc.MethodDefinition<ns_ns_pb.GenerateGatewayClientCertificateRequest, ns_ns_pb.GenerateGatewayClientCertificateResponse>;
  createGatewayProfile: grpc.MethodDefinition<ns_ns_pb.CreateGatewayProfileRequest, ns_ns_pb.CreateGatewayProfileResponse>;
  getGatewayProfile: grpc.MethodDefinition<ns_ns_pb.GetGatewayProfileRequest, ns_ns_pb.GetGatewayProfileResponse>;
  updateGatewayProfile: grpc.MethodDefinition<ns_ns_pb.UpdateGatewayProfileRequest, google_protobuf_empty_pb.Empty>;
  deleteGatewayProfile: grpc.MethodDefinition<ns_ns_pb.DeleteGatewayProfileRequest, google_protobuf_empty_pb.Empty>;
  getGatewayStats: grpc.MethodDefinition<ns_ns_pb.GetGatewayStatsRequest, ns_ns_pb.GetGatewayStatsResponse>;
  streamFrameLogsForGateway: grpc.MethodDefinition<ns_ns_pb.StreamFrameLogsForGatewayRequest, ns_ns_pb.StreamFrameLogsForGatewayResponse>;
  streamFrameLogsForDevice: grpc.MethodDefinition<ns_ns_pb.StreamFrameLogsForDeviceRequest, ns_ns_pb.StreamFrameLogsForDeviceResponse>;
  createMulticastGroup: grpc.MethodDefinition<ns_ns_pb.CreateMulticastGroupRequest, ns_ns_pb.CreateMulticastGroupResponse>;
  getMulticastGroup: grpc.MethodDefinition<ns_ns_pb.GetMulticastGroupRequest, ns_ns_pb.GetMulticastGroupResponse>;
  updateMulticastGroup: grpc.MethodDefinition<ns_ns_pb.UpdateMulticastGroupRequest, google_protobuf_empty_pb.Empty>;
  deleteMulticastGroup: grpc.MethodDefinition<ns_ns_pb.DeleteMulticastGroupRequest, google_protobuf_empty_pb.Empty>;
  addDeviceToMulticastGroup: grpc.MethodDefinition<ns_ns_pb.AddDeviceToMulticastGroupRequest, google_protobuf_empty_pb.Empty>;
  removeDeviceFromMulticastGroup: grpc.MethodDefinition<ns_ns_pb.RemoveDeviceFromMulticastGroupRequest, google_protobuf_empty_pb.Empty>;
  enqueueMulticastQueueItem: grpc.MethodDefinition<ns_ns_pb.EnqueueMulticastQueueItemRequest, google_protobuf_empty_pb.Empty>;
  flushMulticastQueueForMulticastGroup: grpc.MethodDefinition<ns_ns_pb.FlushMulticastQueueForMulticastGroupRequest, google_protobuf_empty_pb.Empty>;
  getMulticastQueueItemsForMulticastGroup: grpc.MethodDefinition<ns_ns_pb.GetMulticastQueueItemsForMulticastGroupRequest, ns_ns_pb.GetMulticastQueueItemsForMulticastGroupResponse>;
  getVersion: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, ns_ns_pb.GetVersionResponse>;
  getADRAlgorithms: grpc.MethodDefinition<google_protobuf_empty_pb.Empty, ns_ns_pb.GetADRAlgorithmsResponse>;
}

export const NetworkServerServiceService: INetworkServerServiceService;

export class NetworkServerServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  createServiceProfile(argument: ns_ns_pb.CreateServiceProfileRequest, callback: grpc.requestCallback<ns_ns_pb.CreateServiceProfileResponse>): grpc.ClientUnaryCall;
  createServiceProfile(argument: ns_ns_pb.CreateServiceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateServiceProfileResponse>): grpc.ClientUnaryCall;
  createServiceProfile(argument: ns_ns_pb.CreateServiceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateServiceProfileResponse>): grpc.ClientUnaryCall;
  getServiceProfile(argument: ns_ns_pb.GetServiceProfileRequest, callback: grpc.requestCallback<ns_ns_pb.GetServiceProfileResponse>): grpc.ClientUnaryCall;
  getServiceProfile(argument: ns_ns_pb.GetServiceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetServiceProfileResponse>): grpc.ClientUnaryCall;
  getServiceProfile(argument: ns_ns_pb.GetServiceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetServiceProfileResponse>): grpc.ClientUnaryCall;
  updateServiceProfile(argument: ns_ns_pb.UpdateServiceProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateServiceProfile(argument: ns_ns_pb.UpdateServiceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateServiceProfile(argument: ns_ns_pb.UpdateServiceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteServiceProfile(argument: ns_ns_pb.DeleteServiceProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteServiceProfile(argument: ns_ns_pb.DeleteServiceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteServiceProfile(argument: ns_ns_pb.DeleteServiceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createRoutingProfile(argument: ns_ns_pb.CreateRoutingProfileRequest, callback: grpc.requestCallback<ns_ns_pb.CreateRoutingProfileResponse>): grpc.ClientUnaryCall;
  createRoutingProfile(argument: ns_ns_pb.CreateRoutingProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateRoutingProfileResponse>): grpc.ClientUnaryCall;
  createRoutingProfile(argument: ns_ns_pb.CreateRoutingProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateRoutingProfileResponse>): grpc.ClientUnaryCall;
  getRoutingProfile(argument: ns_ns_pb.GetRoutingProfileRequest, callback: grpc.requestCallback<ns_ns_pb.GetRoutingProfileResponse>): grpc.ClientUnaryCall;
  getRoutingProfile(argument: ns_ns_pb.GetRoutingProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetRoutingProfileResponse>): grpc.ClientUnaryCall;
  getRoutingProfile(argument: ns_ns_pb.GetRoutingProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetRoutingProfileResponse>): grpc.ClientUnaryCall;
  updateRoutingProfile(argument: ns_ns_pb.UpdateRoutingProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateRoutingProfile(argument: ns_ns_pb.UpdateRoutingProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateRoutingProfile(argument: ns_ns_pb.UpdateRoutingProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteRoutingProfile(argument: ns_ns_pb.DeleteRoutingProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteRoutingProfile(argument: ns_ns_pb.DeleteRoutingProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteRoutingProfile(argument: ns_ns_pb.DeleteRoutingProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDeviceProfile(argument: ns_ns_pb.CreateDeviceProfileRequest, callback: grpc.requestCallback<ns_ns_pb.CreateDeviceProfileResponse>): grpc.ClientUnaryCall;
  createDeviceProfile(argument: ns_ns_pb.CreateDeviceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateDeviceProfileResponse>): grpc.ClientUnaryCall;
  createDeviceProfile(argument: ns_ns_pb.CreateDeviceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateDeviceProfileResponse>): grpc.ClientUnaryCall;
  getDeviceProfile(argument: ns_ns_pb.GetDeviceProfileRequest, callback: grpc.requestCallback<ns_ns_pb.GetDeviceProfileResponse>): grpc.ClientUnaryCall;
  getDeviceProfile(argument: ns_ns_pb.GetDeviceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceProfileResponse>): grpc.ClientUnaryCall;
  getDeviceProfile(argument: ns_ns_pb.GetDeviceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceProfileResponse>): grpc.ClientUnaryCall;
  updateDeviceProfile(argument: ns_ns_pb.UpdateDeviceProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateDeviceProfile(argument: ns_ns_pb.UpdateDeviceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateDeviceProfile(argument: ns_ns_pb.UpdateDeviceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDeviceProfile(argument: ns_ns_pb.DeleteDeviceProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDeviceProfile(argument: ns_ns_pb.DeleteDeviceProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDeviceProfile(argument: ns_ns_pb.DeleteDeviceProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDevice(argument: ns_ns_pb.CreateDeviceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDevice(argument: ns_ns_pb.CreateDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDevice(argument: ns_ns_pb.CreateDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getDevice(argument: ns_ns_pb.GetDeviceRequest, callback: grpc.requestCallback<ns_ns_pb.GetDeviceResponse>): grpc.ClientUnaryCall;
  getDevice(argument: ns_ns_pb.GetDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceResponse>): grpc.ClientUnaryCall;
  getDevice(argument: ns_ns_pb.GetDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceResponse>): grpc.ClientUnaryCall;
  updateDevice(argument: ns_ns_pb.UpdateDeviceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateDevice(argument: ns_ns_pb.UpdateDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateDevice(argument: ns_ns_pb.UpdateDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDevice(argument: ns_ns_pb.DeleteDeviceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDevice(argument: ns_ns_pb.DeleteDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteDevice(argument: ns_ns_pb.DeleteDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  activateDevice(argument: ns_ns_pb.ActivateDeviceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  activateDevice(argument: ns_ns_pb.ActivateDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  activateDevice(argument: ns_ns_pb.ActivateDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deactivateDevice(argument: ns_ns_pb.DeactivateDeviceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deactivateDevice(argument: ns_ns_pb.DeactivateDeviceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deactivateDevice(argument: ns_ns_pb.DeactivateDeviceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getDeviceActivation(argument: ns_ns_pb.GetDeviceActivationRequest, callback: grpc.requestCallback<ns_ns_pb.GetDeviceActivationResponse>): grpc.ClientUnaryCall;
  getDeviceActivation(argument: ns_ns_pb.GetDeviceActivationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceActivationResponse>): grpc.ClientUnaryCall;
  getDeviceActivation(argument: ns_ns_pb.GetDeviceActivationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceActivationResponse>): grpc.ClientUnaryCall;
  createDeviceQueueItem(argument: ns_ns_pb.CreateDeviceQueueItemRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDeviceQueueItem(argument: ns_ns_pb.CreateDeviceQueueItemRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createDeviceQueueItem(argument: ns_ns_pb.CreateDeviceQueueItemRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushDeviceQueueForDevEUI(argument: ns_ns_pb.FlushDeviceQueueForDevEUIRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushDeviceQueueForDevEUI(argument: ns_ns_pb.FlushDeviceQueueForDevEUIRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushDeviceQueueForDevEUI(argument: ns_ns_pb.FlushDeviceQueueForDevEUIRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getDeviceQueueItemsForDevEUI(argument: ns_ns_pb.GetDeviceQueueItemsForDevEUIRequest, callback: grpc.requestCallback<ns_ns_pb.GetDeviceQueueItemsForDevEUIResponse>): grpc.ClientUnaryCall;
  getDeviceQueueItemsForDevEUI(argument: ns_ns_pb.GetDeviceQueueItemsForDevEUIRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceQueueItemsForDevEUIResponse>): grpc.ClientUnaryCall;
  getDeviceQueueItemsForDevEUI(argument: ns_ns_pb.GetDeviceQueueItemsForDevEUIRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetDeviceQueueItemsForDevEUIResponse>): grpc.ClientUnaryCall;
  getNextDownlinkFCntForDevEUI(argument: ns_ns_pb.GetNextDownlinkFCntForDevEUIRequest, callback: grpc.requestCallback<ns_ns_pb.GetNextDownlinkFCntForDevEUIResponse>): grpc.ClientUnaryCall;
  getNextDownlinkFCntForDevEUI(argument: ns_ns_pb.GetNextDownlinkFCntForDevEUIRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetNextDownlinkFCntForDevEUIResponse>): grpc.ClientUnaryCall;
  getNextDownlinkFCntForDevEUI(argument: ns_ns_pb.GetNextDownlinkFCntForDevEUIRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetNextDownlinkFCntForDevEUIResponse>): grpc.ClientUnaryCall;
  getRandomDevAddr(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<ns_ns_pb.GetRandomDevAddrResponse>): grpc.ClientUnaryCall;
  getRandomDevAddr(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetRandomDevAddrResponse>): grpc.ClientUnaryCall;
  getRandomDevAddr(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetRandomDevAddrResponse>): grpc.ClientUnaryCall;
  createMACCommandQueueItem(argument: ns_ns_pb.CreateMACCommandQueueItemRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createMACCommandQueueItem(argument: ns_ns_pb.CreateMACCommandQueueItemRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createMACCommandQueueItem(argument: ns_ns_pb.CreateMACCommandQueueItemRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  sendProprietaryPayload(argument: ns_ns_pb.SendProprietaryPayloadRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  sendProprietaryPayload(argument: ns_ns_pb.SendProprietaryPayloadRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  sendProprietaryPayload(argument: ns_ns_pb.SendProprietaryPayloadRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGateway(argument: ns_ns_pb.CreateGatewayRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGateway(argument: ns_ns_pb.CreateGatewayRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createGateway(argument: ns_ns_pb.CreateGatewayRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getGateway(argument: ns_ns_pb.GetGatewayRequest, callback: grpc.requestCallback<ns_ns_pb.GetGatewayResponse>): grpc.ClientUnaryCall;
  getGateway(argument: ns_ns_pb.GetGatewayRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayResponse>): grpc.ClientUnaryCall;
  getGateway(argument: ns_ns_pb.GetGatewayRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayResponse>): grpc.ClientUnaryCall;
  updateGateway(argument: ns_ns_pb.UpdateGatewayRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGateway(argument: ns_ns_pb.UpdateGatewayRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGateway(argument: ns_ns_pb.UpdateGatewayRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGateway(argument: ns_ns_pb.DeleteGatewayRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGateway(argument: ns_ns_pb.DeleteGatewayRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGateway(argument: ns_ns_pb.DeleteGatewayRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  generateGatewayClientCertificate(argument: ns_ns_pb.GenerateGatewayClientCertificateRequest, callback: grpc.requestCallback<ns_ns_pb.GenerateGatewayClientCertificateResponse>): grpc.ClientUnaryCall;
  generateGatewayClientCertificate(argument: ns_ns_pb.GenerateGatewayClientCertificateRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GenerateGatewayClientCertificateResponse>): grpc.ClientUnaryCall;
  generateGatewayClientCertificate(argument: ns_ns_pb.GenerateGatewayClientCertificateRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GenerateGatewayClientCertificateResponse>): grpc.ClientUnaryCall;
  createGatewayProfile(argument: ns_ns_pb.CreateGatewayProfileRequest, callback: grpc.requestCallback<ns_ns_pb.CreateGatewayProfileResponse>): grpc.ClientUnaryCall;
  createGatewayProfile(argument: ns_ns_pb.CreateGatewayProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateGatewayProfileResponse>): grpc.ClientUnaryCall;
  createGatewayProfile(argument: ns_ns_pb.CreateGatewayProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateGatewayProfileResponse>): grpc.ClientUnaryCall;
  getGatewayProfile(argument: ns_ns_pb.GetGatewayProfileRequest, callback: grpc.requestCallback<ns_ns_pb.GetGatewayProfileResponse>): grpc.ClientUnaryCall;
  getGatewayProfile(argument: ns_ns_pb.GetGatewayProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayProfileResponse>): grpc.ClientUnaryCall;
  getGatewayProfile(argument: ns_ns_pb.GetGatewayProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayProfileResponse>): grpc.ClientUnaryCall;
  updateGatewayProfile(argument: ns_ns_pb.UpdateGatewayProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGatewayProfile(argument: ns_ns_pb.UpdateGatewayProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateGatewayProfile(argument: ns_ns_pb.UpdateGatewayProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGatewayProfile(argument: ns_ns_pb.DeleteGatewayProfileRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGatewayProfile(argument: ns_ns_pb.DeleteGatewayProfileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteGatewayProfile(argument: ns_ns_pb.DeleteGatewayProfileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getGatewayStats(argument: ns_ns_pb.GetGatewayStatsRequest, callback: grpc.requestCallback<ns_ns_pb.GetGatewayStatsResponse>): grpc.ClientUnaryCall;
  getGatewayStats(argument: ns_ns_pb.GetGatewayStatsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayStatsResponse>): grpc.ClientUnaryCall;
  getGatewayStats(argument: ns_ns_pb.GetGatewayStatsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetGatewayStatsResponse>): grpc.ClientUnaryCall;
  streamFrameLogsForGateway(argument: ns_ns_pb.StreamFrameLogsForGatewayRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<ns_ns_pb.StreamFrameLogsForGatewayResponse>;
  streamFrameLogsForGateway(argument: ns_ns_pb.StreamFrameLogsForGatewayRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<ns_ns_pb.StreamFrameLogsForGatewayResponse>;
  streamFrameLogsForDevice(argument: ns_ns_pb.StreamFrameLogsForDeviceRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<ns_ns_pb.StreamFrameLogsForDeviceResponse>;
  streamFrameLogsForDevice(argument: ns_ns_pb.StreamFrameLogsForDeviceRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<ns_ns_pb.StreamFrameLogsForDeviceResponse>;
  createMulticastGroup(argument: ns_ns_pb.CreateMulticastGroupRequest, callback: grpc.requestCallback<ns_ns_pb.CreateMulticastGroupResponse>): grpc.ClientUnaryCall;
  createMulticastGroup(argument: ns_ns_pb.CreateMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateMulticastGroupResponse>): grpc.ClientUnaryCall;
  createMulticastGroup(argument: ns_ns_pb.CreateMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.CreateMulticastGroupResponse>): grpc.ClientUnaryCall;
  getMulticastGroup(argument: ns_ns_pb.GetMulticastGroupRequest, callback: grpc.requestCallback<ns_ns_pb.GetMulticastGroupResponse>): grpc.ClientUnaryCall;
  getMulticastGroup(argument: ns_ns_pb.GetMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetMulticastGroupResponse>): grpc.ClientUnaryCall;
  getMulticastGroup(argument: ns_ns_pb.GetMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetMulticastGroupResponse>): grpc.ClientUnaryCall;
  updateMulticastGroup(argument: ns_ns_pb.UpdateMulticastGroupRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateMulticastGroup(argument: ns_ns_pb.UpdateMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  updateMulticastGroup(argument: ns_ns_pb.UpdateMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMulticastGroup(argument: ns_ns_pb.DeleteMulticastGroupRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMulticastGroup(argument: ns_ns_pb.DeleteMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteMulticastGroup(argument: ns_ns_pb.DeleteMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  addDeviceToMulticastGroup(argument: ns_ns_pb.AddDeviceToMulticastGroupRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  addDeviceToMulticastGroup(argument: ns_ns_pb.AddDeviceToMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  addDeviceToMulticastGroup(argument: ns_ns_pb.AddDeviceToMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  removeDeviceFromMulticastGroup(argument: ns_ns_pb.RemoveDeviceFromMulticastGroupRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  removeDeviceFromMulticastGroup(argument: ns_ns_pb.RemoveDeviceFromMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  removeDeviceFromMulticastGroup(argument: ns_ns_pb.RemoveDeviceFromMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  enqueueMulticastQueueItem(argument: ns_ns_pb.EnqueueMulticastQueueItemRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  enqueueMulticastQueueItem(argument: ns_ns_pb.EnqueueMulticastQueueItemRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  enqueueMulticastQueueItem(argument: ns_ns_pb.EnqueueMulticastQueueItemRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushMulticastQueueForMulticastGroup(argument: ns_ns_pb.FlushMulticastQueueForMulticastGroupRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushMulticastQueueForMulticastGroup(argument: ns_ns_pb.FlushMulticastQueueForMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  flushMulticastQueueForMulticastGroup(argument: ns_ns_pb.FlushMulticastQueueForMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getMulticastQueueItemsForMulticastGroup(argument: ns_ns_pb.GetMulticastQueueItemsForMulticastGroupRequest, callback: grpc.requestCallback<ns_ns_pb.GetMulticastQueueItemsForMulticastGroupResponse>): grpc.ClientUnaryCall;
  getMulticastQueueItemsForMulticastGroup(argument: ns_ns_pb.GetMulticastQueueItemsForMulticastGroupRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetMulticastQueueItemsForMulticastGroupResponse>): grpc.ClientUnaryCall;
  getMulticastQueueItemsForMulticastGroup(argument: ns_ns_pb.GetMulticastQueueItemsForMulticastGroupRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetMulticastQueueItemsForMulticastGroupResponse>): grpc.ClientUnaryCall;
  getVersion(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<ns_ns_pb.GetVersionResponse>): grpc.ClientUnaryCall;
  getVersion(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetVersionResponse>): grpc.ClientUnaryCall;
  getVersion(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetVersionResponse>): grpc.ClientUnaryCall;
  getADRAlgorithms(argument: google_protobuf_empty_pb.Empty, callback: grpc.requestCallback<ns_ns_pb.GetADRAlgorithmsResponse>): grpc.ClientUnaryCall;
  getADRAlgorithms(argument: google_protobuf_empty_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetADRAlgorithmsResponse>): grpc.ClientUnaryCall;
  getADRAlgorithms(argument: google_protobuf_empty_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<ns_ns_pb.GetADRAlgorithmsResponse>): grpc.ClientUnaryCall;
}
