# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geo/geo.proto

require 'google/protobuf'

require 'gw/gw_pb'
require 'common/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("geo/geo.proto", :syntax => :proto3) do
    add_message "geo.ResolveResult" do
      optional :location, :message, 1, "common.Location"
    end
    add_message "geo.FrameRXInfo" do
      repeated :rx_info, :message, 1, "gw.UplinkRXInfo"
    end
    add_message "geo.ResolveTDOARequest" do
      optional :dev_eui, :bytes, 1
      optional :frame_rx_info, :message, 2, "geo.FrameRXInfo"
      optional :device_reference_altitude, :double, 3
    end
    add_message "geo.ResolveMultiFrameTDOARequest" do
      optional :dev_eui, :bytes, 1
      repeated :frame_rx_info_set, :message, 2, "geo.FrameRXInfo"
      optional :device_reference_altitude, :double, 3
    end
    add_message "geo.ResolveTDOAResponse" do
      optional :result, :message, 1, "geo.ResolveResult"
    end
    add_message "geo.ResolveMultiFrameTDOAResponse" do
      optional :result, :message, 1, "geo.ResolveResult"
    end
  end
end

module ChirpStackAPI
  module Geo
    ResolveResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.ResolveResult").msgclass
    FrameRXInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.FrameRXInfo").msgclass
    ResolveTDOARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.ResolveTDOARequest").msgclass
    ResolveMultiFrameTDOARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.ResolveMultiFrameTDOARequest").msgclass
    ResolveTDOAResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.ResolveTDOAResponse").msgclass
    ResolveMultiFrameTDOAResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("geo.ResolveMultiFrameTDOAResponse").msgclass
  end
end
