"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import chirpstack_api.common.common_pb2
import chirpstack_api.gw.gw_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper):
    pass
class _ErrorType:
    V = typing.NewType('V', builtins.int)
class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    # Unknown type.
    UNKNOWN = ErrorType.V(0)
    # Error related to the downlink payload size.
    # Usually seen when the payload exceeded the maximum allowed payload size.
    DOWNLINK_PAYLOAD_SIZE = ErrorType.V(1)
    # Error related to the downlink frame-counter.
    # Usually seen when the frame-counter has already been used.
    DOWNLINK_FCNT = ErrorType.V(2)
    # Uplink codec error.
    UPLINK_CODEC = ErrorType.V(3)
    # Downlink codec error.
    DOWNLINK_CODEC = ErrorType.V(4)
    # OTAA error.
    OTAA = ErrorType.V(5)
    # Uplink frame-counter was reset.
    UPLINK_FCNT_RESET = ErrorType.V(6)
    # Uplink MIC error.
    UPLINK_MIC = ErrorType.V(7)
    # Uplink frame-counter retransmission.
    UPLINK_FCNT_RETRANSMISSION = ErrorType.V(8)
    # Downlink gateway error.
    DOWNLINK_GATEWAY = ErrorType.V(9)

# Unknown type.
UNKNOWN = ErrorType.V(0)
# Error related to the downlink payload size.
# Usually seen when the payload exceeded the maximum allowed payload size.
DOWNLINK_PAYLOAD_SIZE = ErrorType.V(1)
# Error related to the downlink frame-counter.
# Usually seen when the frame-counter has already been used.
DOWNLINK_FCNT = ErrorType.V(2)
# Uplink codec error.
UPLINK_CODEC = ErrorType.V(3)
# Downlink codec error.
DOWNLINK_CODEC = ErrorType.V(4)
# OTAA error.
OTAA = ErrorType.V(5)
# Uplink frame-counter was reset.
UPLINK_FCNT_RESET = ErrorType.V(6)
# Uplink MIC error.
UPLINK_MIC = ErrorType.V(7)
# Uplink frame-counter retransmission.
UPLINK_FCNT_RETRANSMISSION = ErrorType.V(8)
# Downlink gateway error.
DOWNLINK_GATEWAY = ErrorType.V(9)
global___ErrorType = ErrorType


# UplinkEvent is the message sent when an uplink payload has been received.
class UplinkEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    RX_INFO_FIELD_NUMBER: builtins.int
    TX_INFO_FIELD_NUMBER: builtins.int
    ADR_FIELD_NUMBER: builtins.int
    DR_FIELD_NUMBER: builtins.int
    F_CNT_FIELD_NUMBER: builtins.int
    F_PORT_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    OBJECT_JSON_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    CONFIRMED_UPLINK_FIELD_NUMBER: builtins.int
    DEV_ADDR_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    DEVICE_PROFILE_ID_FIELD_NUMBER: builtins.int
    DEVICE_PROFILE_NAME_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Receiving gateway RX info.
    @property
    def rx_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[chirpstack_api.gw.gw_pb2.UplinkRXInfo]: ...
    # TX info.
    @property
    def tx_info(self) -> chirpstack_api.gw.gw_pb2.UplinkTXInfo: ...
    # Device has ADR bit set.
    adr: builtins.bool = ...
    # Data-rate.
    dr: builtins.int = ...
    # Frame counter.
    f_cnt: builtins.int = ...
    # Frame port.
    f_port: builtins.int = ...
    # FRMPayload data.
    data: builtins.bytes = ...
    # JSON string containing the decoded object.
    # Note that this is only set when a codec is configured in the Device Profile.
    object_json: typing.Text = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Uplink was of type confirmed.
    confirmed_uplink: builtins.bool = ...
    # Device address.
    dev_addr: builtins.bytes = ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    # Device Profile UUID as string
    device_profile_id: typing.Text = ...
    # Device Profile name
    device_profile_name: typing.Text = ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        rx_info : typing.Optional[typing.Iterable[chirpstack_api.gw.gw_pb2.UplinkRXInfo]] = ...,
        tx_info : typing.Optional[chirpstack_api.gw.gw_pb2.UplinkTXInfo] = ...,
        adr : builtins.bool = ...,
        dr : builtins.int = ...,
        f_cnt : builtins.int = ...,
        f_port : builtins.int = ...,
        data : builtins.bytes = ...,
        object_json : typing.Text = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        confirmed_uplink : builtins.bool = ...,
        dev_addr : builtins.bytes = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        device_profile_id : typing.Text = ...,
        device_profile_name : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at",u"tx_info",b"tx_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"adr",b"adr",u"application_id",b"application_id",u"application_name",b"application_name",u"confirmed_uplink",b"confirmed_uplink",u"data",b"data",u"dev_addr",b"dev_addr",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"device_profile_id",b"device_profile_id",u"device_profile_name",b"device_profile_name",u"dr",b"dr",u"f_cnt",b"f_cnt",u"f_port",b"f_port",u"object_json",b"object_json",u"published_at",b"published_at",u"rx_info",b"rx_info",u"tags",b"tags",u"tx_info",b"tx_info"]) -> None: ...
global___UplinkEvent = UplinkEvent

# JoinEvent is the message sent when a device joined the network.
# Note that this is only sent after the first received uplink after the
# device (re)activation.
class JoinEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    DEV_ADDR_FIELD_NUMBER: builtins.int
    RX_INFO_FIELD_NUMBER: builtins.int
    TX_INFO_FIELD_NUMBER: builtins.int
    DR_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Device address.
    dev_addr: builtins.bytes = ...
    # Receiving gateway RX info.
    @property
    def rx_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[chirpstack_api.gw.gw_pb2.UplinkRXInfo]: ...
    # TX info.
    @property
    def tx_info(self) -> chirpstack_api.gw.gw_pb2.UplinkTXInfo: ...
    # Data-rate.
    dr: builtins.int = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        dev_addr : builtins.bytes = ...,
        rx_info : typing.Optional[typing.Iterable[chirpstack_api.gw.gw_pb2.UplinkRXInfo]] = ...,
        tx_info : typing.Optional[chirpstack_api.gw.gw_pb2.UplinkTXInfo] = ...,
        dr : builtins.int = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at",u"tx_info",b"tx_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"dev_addr",b"dev_addr",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"dr",b"dr",u"published_at",b"published_at",u"rx_info",b"rx_info",u"tags",b"tags",u"tx_info",b"tx_info"]) -> None: ...
global___JoinEvent = JoinEvent

# AckEvent is the message sent when a confirmation on a confirmed downlink
# has been received -or- when the downlink timed out.
class AckEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    ACKNOWLEDGED_FIELD_NUMBER: builtins.int
    F_CNT_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Frame was acknowledged.
    acknowledged: builtins.bool = ...
    # Downlink frame counter to which the acknowledgement relates.
    f_cnt: builtins.int = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        acknowledged : builtins.bool = ...,
        f_cnt : builtins.int = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"acknowledged",b"acknowledged",u"application_id",b"application_id",u"application_name",b"application_name",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"f_cnt",b"f_cnt",u"published_at",b"published_at",u"tags",b"tags"]) -> None: ...
global___AckEvent = AckEvent

# TxAckEvent is the message sent when a downlink was acknowledged by the gateway
# for transmission. As a downlink can be scheduled in the future, this event
# does not confirm that the message has already been transmitted.
class TxAckEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    F_CNT_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    GATEWAY_ID_FIELD_NUMBER: builtins.int
    TX_INFO_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Downlink frame-counter.
    f_cnt: builtins.int = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Gateway ID.
    gateway_id: builtins.bytes = ...
    # TX info.
    @property
    def tx_info(self) -> chirpstack_api.gw.gw_pb2.DownlinkTXInfo: ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        f_cnt : builtins.int = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        gateway_id : builtins.bytes = ...,
        tx_info : typing.Optional[chirpstack_api.gw.gw_pb2.DownlinkTXInfo] = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at",u"tx_info",b"tx_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"f_cnt",b"f_cnt",u"gateway_id",b"gateway_id",u"published_at",b"published_at",u"tags",b"tags",u"tx_info",b"tx_info"]) -> None: ...
global___TxAckEvent = TxAckEvent

# ErrorEvent is the message sent when an error occurred.
class ErrorEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    F_CNT_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Error type.
    type: global___ErrorType.V = ...
    # Error message.
    error: typing.Text = ...
    # Downlink frame-counter (in case the downlink is related to a scheduled downlink).
    f_cnt: builtins.int = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        type : global___ErrorType.V = ...,
        error : typing.Text = ...,
        f_cnt : builtins.int = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"error",b"error",u"f_cnt",b"f_cnt",u"published_at",b"published_at",u"tags",b"tags",u"type",b"type"]) -> None: ...
global___ErrorEvent = ErrorEvent

# StatusEvent is the message sent when a device-status mac-command was sent
# by the device.
class StatusEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    MARGIN_FIELD_NUMBER: builtins.int
    EXTERNAL_POWER_SOURCE_FIELD_NUMBER: builtins.int
    BATTERY_LEVEL_UNAVAILABLE_FIELD_NUMBER: builtins.int
    BATTERY_LEVEL_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # The demodulation signal-to-noise ratio in dB for the last successfully
    # received device-status request by the Network Server.
    margin: builtins.int = ...
    # Device is connected to an external power source.
    external_power_source: builtins.bool = ...
    # Battery level is not available.
    battery_level_unavailable: builtins.bool = ...
    # Battery level.
    battery_level: builtins.float = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        margin : builtins.int = ...,
        external_power_source : builtins.bool = ...,
        battery_level_unavailable : builtins.bool = ...,
        battery_level : builtins.float = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"battery_level",b"battery_level",u"battery_level_unavailable",b"battery_level_unavailable",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"external_power_source",b"external_power_source",u"margin",b"margin",u"published_at",b"published_at",u"tags",b"tags"]) -> None: ...
global___StatusEvent = StatusEvent

# LocationEvent is the message sent when a geolocation resolve was returned.
class LocationEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    UPLINK_IDS_FIELD_NUMBER: builtins.int
    F_CNT_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # Location.
    @property
    def location(self) -> chirpstack_api.common.common_pb2.Location: ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Uplink IDs used for geolocation.
    # This is set in case the geolocation is based on the uplink meta-data.
    @property
    def uplink_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    # Frame counter (in case the geolocation is based on the payload).
    # This is set in case the geolocation is based on the uplink payload content.
    f_cnt: builtins.int = ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        location : typing.Optional[chirpstack_api.common.common_pb2.Location] = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        uplink_ids : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        f_cnt : builtins.int = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"location",b"location",u"published_at",b"published_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"f_cnt",b"f_cnt",u"location",b"location",u"published_at",b"published_at",u"tags",b"tags",u"uplink_ids",b"uplink_ids"]) -> None: ...
global___LocationEvent = LocationEvent

# IntegrationEvent is the message that can be sent by an integration.
# It allows for sending events which are provided by an external integration
# which are "not native" to ChirpStack.
class IntegrationEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    APPLICATION_ID_FIELD_NUMBER: builtins.int
    APPLICATION_NAME_FIELD_NUMBER: builtins.int
    DEVICE_NAME_FIELD_NUMBER: builtins.int
    DEV_EUI_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    INTEGRATION_NAME_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    OBJECT_JSON_FIELD_NUMBER: builtins.int
    PUBLISHED_AT_FIELD_NUMBER: builtins.int
    # Application ID.
    application_id: builtins.int = ...
    # Application name.
    application_name: typing.Text = ...
    # Device name.
    device_name: typing.Text = ...
    # Device EUI.
    dev_eui: builtins.bytes = ...
    # User-defined device tags.
    @property
    def tags(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    # Integration name.
    integration_name: typing.Text = ...
    # Event type.
    event_type: typing.Text = ...
    # JSON string containing the event object.
    object_json: typing.Text = ...
    # Published at timestamp.
    @property
    def published_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        application_id : builtins.int = ...,
        application_name : typing.Text = ...,
        device_name : typing.Text = ...,
        dev_eui : builtins.bytes = ...,
        tags : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        integration_name : typing.Text = ...,
        event_type : typing.Text = ...,
        object_json : typing.Text = ...,
        published_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"published_at",b"published_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_id",b"application_id",u"application_name",b"application_name",u"dev_eui",b"dev_eui",u"device_name",b"device_name",u"event_type",b"event_type",u"integration_name",b"integration_name",u"object_json",b"object_json",u"published_at",b"published_at",u"tags",b"tags"]) -> None: ...
global___IntegrationEvent = IntegrationEvent
