// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nc/nc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chirpstack.NetworkController {

  /// <summary>Holder for reflection information generated from nc/nc.proto</summary>
  public static partial class NcReflection {

    #region Descriptor
    /// <summary>File descriptor for nc/nc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtuYy9uYy5wcm90bxICbmMaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90",
            "bxoLZ3cvZ3cucHJvdG8i/QEKG0hhbmRsZVVwbGlua01ldGFEYXRhUmVxdWVz",
            "dBIPCgdkZXZfZXVpGAEgASgMEiEKB3R4X2luZm8YAiABKAsyEC5ndy5VcGxp",
            "bmtUWEluZm8SIQoHcnhfaW5mbxgDIAMoCzIQLmd3LlVwbGlua1JYSW5mbxIe",
            "ChZwaHlfcGF5bG9hZF9ieXRlX2NvdW50GAQgASgNEh4KFm1hY19jb21tYW5k",
            "X2J5dGVfY291bnQYBSABKA0SJgoeYXBwbGljYXRpb25fcGF5bG9hZF9ieXRl",
            "X2NvdW50GAYgASgNEh8KDG1lc3NhZ2VfdHlwZRgHIAEoDjIJLm5jLk1UeXBl",
            "Io4CCh1IYW5kbGVEb3dubGlua01ldGFEYXRhUmVxdWVzdBIPCgdkZXZfZXVp",
            "GAEgASgMEhoKEm11bHRpY2FzdF9ncm91cF9pZBgCIAEoDBIjCgd0eF9pbmZv",
            "GAMgASgLMhIuZ3cuRG93bmxpbmtUWEluZm8SHgoWcGh5X3BheWxvYWRfYnl0",
            "ZV9jb3VudBgEIAEoDRIeChZtYWNfY29tbWFuZF9ieXRlX2NvdW50GAUgASgN",
            "EiYKHmFwcGxpY2F0aW9uX3BheWxvYWRfYnl0ZV9jb3VudBgGIAEoDRIfCgxt",
            "ZXNzYWdlX3R5cGUYByABKA4yCS5uYy5NVHlwZRISCgpnYXRld2F5X2lkGAgg",
            "ASgMIk8KHUhhbmRsZVVwbGlua01BQ0NvbW1hbmRSZXF1ZXN0Eg8KB2Rldl9l",
            "dWkYASABKAwSCwoDY2lkGAIgASgNEhAKCGNvbW1hbmRzGAYgAygMIkwKI0hh",
            "bmRsZVJlamVjdGVkVXBsaW5rRnJhbWVTZXRSZXF1ZXN0EiUKCWZyYW1lX3Nl",
            "dBgBIAEoCzISLmd3LlVwbGlua0ZyYW1lU2V0Kq8BCgVNVHlwZRILCgdVTktO",
            "T1dOEAASEAoMSk9JTl9SRVFVRVNUEAESDwoLSk9JTl9BQ0NFUFQQAhIXChNV",
            "TkNPTkZJUk1FRF9EQVRBX1VQEAMSGQoVVU5DT05GSVJNRURfREFUQV9ET1dO",
            "EAQSFQoRQ09ORklSTUVEX0RBVEFfVVAQBRIXChNDT05GSVJNRURfREFUQV9E",
            "T1dOEAYSEgoOUkVKT0lOX1JFUVVFU1QQBzL+AgoYTmV0d29ya0NvbnRyb2xs",
            "ZXJTZXJ2aWNlElEKFEhhbmRsZVVwbGlua01ldGFEYXRhEh8ubmMuSGFuZGxl",
            "VXBsaW5rTWV0YURhdGFSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5",
            "IgASVQoWSGFuZGxlRG93bmxpbmtNZXRhRGF0YRIhLm5jLkhhbmRsZURvd25s",
            "aW5rTWV0YURhdGFSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgAS",
            "VQoWSGFuZGxlVXBsaW5rTUFDQ29tbWFuZBIhLm5jLkhhbmRsZVVwbGlua01B",
            "Q0NvbW1hbmRSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASYQoc",
            "SGFuZGxlUmVqZWN0ZWRVcGxpbmtGcmFtZVNldBInLm5jLkhhbmRsZVJlamVj",
            "dGVkVXBsaW5rRnJhbWVTZXRSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5IgBCewoUaW8uY2hpcnBzdGFjay5hcGkubmNCFk5ldHdvcmtDb250cm9s",
            "bGVyUHJvdG9QAVoqZ2l0aHViLmNvbS9icm9jYWFyL2NoaXJwc3RhY2stYXBp",
            "L2dvL3YzL25jqgIcQ2hpcnBzdGFjay5OZXR3b3JrQ29udHJvbGxlcmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Chirpstack.Gateway.GwReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Chirpstack.NetworkController.MType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.NetworkController.HandleUplinkMetaDataRequest), global::Chirpstack.NetworkController.HandleUplinkMetaDataRequest.Parser, new[]{ "DevEui", "TxInfo", "RxInfo", "PhyPayloadByteCount", "MacCommandByteCount", "ApplicationPayloadByteCount", "MessageType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.NetworkController.HandleDownlinkMetaDataRequest), global::Chirpstack.NetworkController.HandleDownlinkMetaDataRequest.Parser, new[]{ "DevEui", "MulticastGroupId", "TxInfo", "PhyPayloadByteCount", "MacCommandByteCount", "ApplicationPayloadByteCount", "MessageType", "GatewayId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.NetworkController.HandleUplinkMACCommandRequest), global::Chirpstack.NetworkController.HandleUplinkMACCommandRequest.Parser, new[]{ "DevEui", "Cid", "Commands" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chirpstack.NetworkController.HandleRejectedUplinkFrameSetRequest), global::Chirpstack.NetworkController.HandleRejectedUplinkFrameSetRequest.Parser, new[]{ "FrameSet" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("JOIN_REQUEST")] JoinRequest = 1,
    [pbr::OriginalName("JOIN_ACCEPT")] JoinAccept = 2,
    [pbr::OriginalName("UNCONFIRMED_DATA_UP")] UnconfirmedDataUp = 3,
    [pbr::OriginalName("UNCONFIRMED_DATA_DOWN")] UnconfirmedDataDown = 4,
    [pbr::OriginalName("CONFIRMED_DATA_UP")] ConfirmedDataUp = 5,
    [pbr::OriginalName("CONFIRMED_DATA_DOWN")] ConfirmedDataDown = 6,
    [pbr::OriginalName("REJOIN_REQUEST")] RejoinRequest = 7,
  }

  #endregion

  #region Messages
  public sealed partial class HandleUplinkMetaDataRequest : pb::IMessage<HandleUplinkMetaDataRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandleUplinkMetaDataRequest> _parser = new pb::MessageParser<HandleUplinkMetaDataRequest>(() => new HandleUplinkMetaDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandleUplinkMetaDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.NetworkController.NcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMetaDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMetaDataRequest(HandleUplinkMetaDataRequest other) : this() {
      devEui_ = other.devEui_;
      txInfo_ = other.txInfo_ != null ? other.txInfo_.Clone() : null;
      rxInfo_ = other.rxInfo_.Clone();
      phyPayloadByteCount_ = other.phyPayloadByteCount_;
      macCommandByteCount_ = other.macCommandByteCount_;
      applicationPayloadByteCount_ = other.applicationPayloadByteCount_;
      messageType_ = other.messageType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMetaDataRequest Clone() {
      return new HandleUplinkMetaDataRequest(this);
    }

    /// <summary>Field number for the "dev_eui" field.</summary>
    public const int DevEuiFieldNumber = 1;
    private pb::ByteString devEui_ = pb::ByteString.Empty;
    /// <summary>
    /// Device EUI (8 bytes).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DevEui {
      get { return devEui_; }
      set {
        devEui_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_info" field.</summary>
    public const int TxInfoFieldNumber = 2;
    private global::Chirpstack.Gateway.UplinkTXInfo txInfo_;
    /// <summary>
    /// TX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Gateway.UplinkTXInfo TxInfo {
      get { return txInfo_; }
      set {
        txInfo_ = value;
      }
    }

    /// <summary>Field number for the "rx_info" field.</summary>
    public const int RxInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Chirpstack.Gateway.UplinkRXInfo> _repeated_rxInfo_codec
        = pb::FieldCodec.ForMessage(26, global::Chirpstack.Gateway.UplinkRXInfo.Parser);
    private readonly pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRXInfo> rxInfo_ = new pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRXInfo>();
    /// <summary>
    /// RX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Chirpstack.Gateway.UplinkRXInfo> RxInfo {
      get { return rxInfo_; }
    }

    /// <summary>Field number for the "phy_payload_byte_count" field.</summary>
    public const int PhyPayloadByteCountFieldNumber = 4;
    private uint phyPayloadByteCount_;
    /// <summary>
    /// PHYPayload byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PhyPayloadByteCount {
      get { return phyPayloadByteCount_; }
      set {
        phyPayloadByteCount_ = value;
      }
    }

    /// <summary>Field number for the "mac_command_byte_count" field.</summary>
    public const int MacCommandByteCountFieldNumber = 5;
    private uint macCommandByteCount_;
    /// <summary>
    /// MAC-Command byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MacCommandByteCount {
      get { return macCommandByteCount_; }
      set {
        macCommandByteCount_ = value;
      }
    }

    /// <summary>Field number for the "application_payload_byte_count" field.</summary>
    public const int ApplicationPayloadByteCountFieldNumber = 6;
    private uint applicationPayloadByteCount_;
    /// <summary>
    /// Application payload byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ApplicationPayloadByteCount {
      get { return applicationPayloadByteCount_; }
      set {
        applicationPayloadByteCount_ = value;
      }
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 7;
    private global::Chirpstack.NetworkController.MType messageType_ = global::Chirpstack.NetworkController.MType.Unknown;
    /// <summary>
    /// Message type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.NetworkController.MType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandleUplinkMetaDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandleUplinkMetaDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DevEui != other.DevEui) return false;
      if (!object.Equals(TxInfo, other.TxInfo)) return false;
      if(!rxInfo_.Equals(other.rxInfo_)) return false;
      if (PhyPayloadByteCount != other.PhyPayloadByteCount) return false;
      if (MacCommandByteCount != other.MacCommandByteCount) return false;
      if (ApplicationPayloadByteCount != other.ApplicationPayloadByteCount) return false;
      if (MessageType != other.MessageType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DevEui.Length != 0) hash ^= DevEui.GetHashCode();
      if (txInfo_ != null) hash ^= TxInfo.GetHashCode();
      hash ^= rxInfo_.GetHashCode();
      if (PhyPayloadByteCount != 0) hash ^= PhyPayloadByteCount.GetHashCode();
      if (MacCommandByteCount != 0) hash ^= MacCommandByteCount.GetHashCode();
      if (ApplicationPayloadByteCount != 0) hash ^= ApplicationPayloadByteCount.GetHashCode();
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) hash ^= MessageType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TxInfo);
      }
      rxInfo_.WriteTo(output, _repeated_rxInfo_codec);
      if (PhyPayloadByteCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MessageType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TxInfo);
      }
      rxInfo_.WriteTo(ref output, _repeated_rxInfo_codec);
      if (PhyPayloadByteCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MessageType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DevEui.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DevEui);
      }
      if (txInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TxInfo);
      }
      size += rxInfo_.CalculateSize(_repeated_rxInfo_codec);
      if (PhyPayloadByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandleUplinkMetaDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.DevEui.Length != 0) {
        DevEui = other.DevEui;
      }
      if (other.txInfo_ != null) {
        if (txInfo_ == null) {
          TxInfo = new global::Chirpstack.Gateway.UplinkTXInfo();
        }
        TxInfo.MergeFrom(other.TxInfo);
      }
      rxInfo_.Add(other.rxInfo_);
      if (other.PhyPayloadByteCount != 0) {
        PhyPayloadByteCount = other.PhyPayloadByteCount;
      }
      if (other.MacCommandByteCount != 0) {
        MacCommandByteCount = other.MacCommandByteCount;
      }
      if (other.ApplicationPayloadByteCount != 0) {
        ApplicationPayloadByteCount = other.ApplicationPayloadByteCount;
      }
      if (other.MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        MessageType = other.MessageType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 18: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.UplinkTXInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 26: {
            rxInfo_.AddEntriesFrom(input, _repeated_rxInfo_codec);
            break;
          }
          case 32: {
            PhyPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MacCommandByteCount = input.ReadUInt32();
            break;
          }
          case 48: {
            ApplicationPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MessageType = (global::Chirpstack.NetworkController.MType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 18: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.UplinkTXInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 26: {
            rxInfo_.AddEntriesFrom(ref input, _repeated_rxInfo_codec);
            break;
          }
          case 32: {
            PhyPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MacCommandByteCount = input.ReadUInt32();
            break;
          }
          case 48: {
            ApplicationPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MessageType = (global::Chirpstack.NetworkController.MType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HandleDownlinkMetaDataRequest : pb::IMessage<HandleDownlinkMetaDataRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandleDownlinkMetaDataRequest> _parser = new pb::MessageParser<HandleDownlinkMetaDataRequest>(() => new HandleDownlinkMetaDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandleDownlinkMetaDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.NetworkController.NcReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleDownlinkMetaDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleDownlinkMetaDataRequest(HandleDownlinkMetaDataRequest other) : this() {
      devEui_ = other.devEui_;
      multicastGroupId_ = other.multicastGroupId_;
      txInfo_ = other.txInfo_ != null ? other.txInfo_.Clone() : null;
      phyPayloadByteCount_ = other.phyPayloadByteCount_;
      macCommandByteCount_ = other.macCommandByteCount_;
      applicationPayloadByteCount_ = other.applicationPayloadByteCount_;
      messageType_ = other.messageType_;
      gatewayId_ = other.gatewayId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleDownlinkMetaDataRequest Clone() {
      return new HandleDownlinkMetaDataRequest(this);
    }

    /// <summary>Field number for the "dev_eui" field.</summary>
    public const int DevEuiFieldNumber = 1;
    private pb::ByteString devEui_ = pb::ByteString.Empty;
    /// <summary>
    /// Device EUI (8 bytes).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DevEui {
      get { return devEui_; }
      set {
        devEui_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "multicast_group_id" field.</summary>
    public const int MulticastGroupIdFieldNumber = 2;
    private pb::ByteString multicastGroupId_ = pb::ByteString.Empty;
    /// <summary>
    /// Multicast Group ID (UUID).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString MulticastGroupId {
      get { return multicastGroupId_; }
      set {
        multicastGroupId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tx_info" field.</summary>
    public const int TxInfoFieldNumber = 3;
    private global::Chirpstack.Gateway.DownlinkTXInfo txInfo_;
    /// <summary>
    /// TX meta-data.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Gateway.DownlinkTXInfo TxInfo {
      get { return txInfo_; }
      set {
        txInfo_ = value;
      }
    }

    /// <summary>Field number for the "phy_payload_byte_count" field.</summary>
    public const int PhyPayloadByteCountFieldNumber = 4;
    private uint phyPayloadByteCount_;
    /// <summary>
    /// PHYPayload byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PhyPayloadByteCount {
      get { return phyPayloadByteCount_; }
      set {
        phyPayloadByteCount_ = value;
      }
    }

    /// <summary>Field number for the "mac_command_byte_count" field.</summary>
    public const int MacCommandByteCountFieldNumber = 5;
    private uint macCommandByteCount_;
    /// <summary>
    /// MAC-Command byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MacCommandByteCount {
      get { return macCommandByteCount_; }
      set {
        macCommandByteCount_ = value;
      }
    }

    /// <summary>Field number for the "application_payload_byte_count" field.</summary>
    public const int ApplicationPayloadByteCountFieldNumber = 6;
    private uint applicationPayloadByteCount_;
    /// <summary>
    /// Application payload byte count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ApplicationPayloadByteCount {
      get { return applicationPayloadByteCount_; }
      set {
        applicationPayloadByteCount_ = value;
      }
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 7;
    private global::Chirpstack.NetworkController.MType messageType_ = global::Chirpstack.NetworkController.MType.Unknown;
    /// <summary>
    /// Message type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.NetworkController.MType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "gateway_id" field.</summary>
    public const int GatewayIdFieldNumber = 8;
    private pb::ByteString gatewayId_ = pb::ByteString.Empty;
    /// <summary>
    /// Gateway ID.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString GatewayId {
      get { return gatewayId_; }
      set {
        gatewayId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandleDownlinkMetaDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandleDownlinkMetaDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DevEui != other.DevEui) return false;
      if (MulticastGroupId != other.MulticastGroupId) return false;
      if (!object.Equals(TxInfo, other.TxInfo)) return false;
      if (PhyPayloadByteCount != other.PhyPayloadByteCount) return false;
      if (MacCommandByteCount != other.MacCommandByteCount) return false;
      if (ApplicationPayloadByteCount != other.ApplicationPayloadByteCount) return false;
      if (MessageType != other.MessageType) return false;
      if (GatewayId != other.GatewayId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DevEui.Length != 0) hash ^= DevEui.GetHashCode();
      if (MulticastGroupId.Length != 0) hash ^= MulticastGroupId.GetHashCode();
      if (txInfo_ != null) hash ^= TxInfo.GetHashCode();
      if (PhyPayloadByteCount != 0) hash ^= PhyPayloadByteCount.GetHashCode();
      if (MacCommandByteCount != 0) hash ^= MacCommandByteCount.GetHashCode();
      if (ApplicationPayloadByteCount != 0) hash ^= ApplicationPayloadByteCount.GetHashCode();
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) hash ^= MessageType.GetHashCode();
      if (GatewayId.Length != 0) hash ^= GatewayId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (MulticastGroupId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(MulticastGroupId);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TxInfo);
      }
      if (PhyPayloadByteCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MessageType);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(GatewayId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (MulticastGroupId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(MulticastGroupId);
      }
      if (txInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TxInfo);
      }
      if (PhyPayloadByteCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MessageType);
      }
      if (GatewayId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(GatewayId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DevEui.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DevEui);
      }
      if (MulticastGroupId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MulticastGroupId);
      }
      if (txInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TxInfo);
      }
      if (PhyPayloadByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PhyPayloadByteCount);
      }
      if (MacCommandByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MacCommandByteCount);
      }
      if (ApplicationPayloadByteCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ApplicationPayloadByteCount);
      }
      if (MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (GatewayId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(GatewayId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandleDownlinkMetaDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.DevEui.Length != 0) {
        DevEui = other.DevEui;
      }
      if (other.MulticastGroupId.Length != 0) {
        MulticastGroupId = other.MulticastGroupId;
      }
      if (other.txInfo_ != null) {
        if (txInfo_ == null) {
          TxInfo = new global::Chirpstack.Gateway.DownlinkTXInfo();
        }
        TxInfo.MergeFrom(other.TxInfo);
      }
      if (other.PhyPayloadByteCount != 0) {
        PhyPayloadByteCount = other.PhyPayloadByteCount;
      }
      if (other.MacCommandByteCount != 0) {
        MacCommandByteCount = other.MacCommandByteCount;
      }
      if (other.ApplicationPayloadByteCount != 0) {
        ApplicationPayloadByteCount = other.ApplicationPayloadByteCount;
      }
      if (other.MessageType != global::Chirpstack.NetworkController.MType.Unknown) {
        MessageType = other.MessageType;
      }
      if (other.GatewayId.Length != 0) {
        GatewayId = other.GatewayId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 18: {
            MulticastGroupId = input.ReadBytes();
            break;
          }
          case 26: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.DownlinkTXInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 32: {
            PhyPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MacCommandByteCount = input.ReadUInt32();
            break;
          }
          case 48: {
            ApplicationPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MessageType = (global::Chirpstack.NetworkController.MType) input.ReadEnum();
            break;
          }
          case 66: {
            GatewayId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 18: {
            MulticastGroupId = input.ReadBytes();
            break;
          }
          case 26: {
            if (txInfo_ == null) {
              TxInfo = new global::Chirpstack.Gateway.DownlinkTXInfo();
            }
            input.ReadMessage(TxInfo);
            break;
          }
          case 32: {
            PhyPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MacCommandByteCount = input.ReadUInt32();
            break;
          }
          case 48: {
            ApplicationPayloadByteCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MessageType = (global::Chirpstack.NetworkController.MType) input.ReadEnum();
            break;
          }
          case 66: {
            GatewayId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HandleUplinkMACCommandRequest : pb::IMessage<HandleUplinkMACCommandRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandleUplinkMACCommandRequest> _parser = new pb::MessageParser<HandleUplinkMACCommandRequest>(() => new HandleUplinkMACCommandRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandleUplinkMACCommandRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.NetworkController.NcReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMACCommandRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMACCommandRequest(HandleUplinkMACCommandRequest other) : this() {
      devEui_ = other.devEui_;
      cid_ = other.cid_;
      commands_ = other.commands_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleUplinkMACCommandRequest Clone() {
      return new HandleUplinkMACCommandRequest(this);
    }

    /// <summary>Field number for the "dev_eui" field.</summary>
    public const int DevEuiFieldNumber = 1;
    private pb::ByteString devEui_ = pb::ByteString.Empty;
    /// <summary>
    /// Device EUI (8 bytes).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DevEui {
      get { return devEui_; }
      set {
        devEui_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 2;
    private uint cid_;
    /// <summary>
    /// Command identifier (specified by the LoRaWAN specs).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "commands" field.</summary>
    public const int CommandsFieldNumber = 6;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_commands_codec
        = pb::FieldCodec.ForBytes(50);
    private readonly pbc::RepeatedField<pb::ByteString> commands_ = new pbc::RepeatedField<pb::ByteString>();
    /// <summary>
    /// MAC-command payload(s).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> Commands {
      get { return commands_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandleUplinkMACCommandRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandleUplinkMACCommandRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DevEui != other.DevEui) return false;
      if (Cid != other.Cid) return false;
      if(!commands_.Equals(other.commands_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DevEui.Length != 0) hash ^= DevEui.GetHashCode();
      if (Cid != 0) hash ^= Cid.GetHashCode();
      hash ^= commands_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (Cid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cid);
      }
      commands_.WriteTo(output, _repeated_commands_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DevEui.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(DevEui);
      }
      if (Cid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cid);
      }
      commands_.WriteTo(ref output, _repeated_commands_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DevEui.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DevEui);
      }
      if (Cid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Cid);
      }
      size += commands_.CalculateSize(_repeated_commands_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandleUplinkMACCommandRequest other) {
      if (other == null) {
        return;
      }
      if (other.DevEui.Length != 0) {
        DevEui = other.DevEui;
      }
      if (other.Cid != 0) {
        Cid = other.Cid;
      }
      commands_.Add(other.commands_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 16: {
            Cid = input.ReadUInt32();
            break;
          }
          case 50: {
            commands_.AddEntriesFrom(input, _repeated_commands_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DevEui = input.ReadBytes();
            break;
          }
          case 16: {
            Cid = input.ReadUInt32();
            break;
          }
          case 50: {
            commands_.AddEntriesFrom(ref input, _repeated_commands_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HandleRejectedUplinkFrameSetRequest : pb::IMessage<HandleRejectedUplinkFrameSetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HandleRejectedUplinkFrameSetRequest> _parser = new pb::MessageParser<HandleRejectedUplinkFrameSetRequest>(() => new HandleRejectedUplinkFrameSetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HandleRejectedUplinkFrameSetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chirpstack.NetworkController.NcReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleRejectedUplinkFrameSetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleRejectedUplinkFrameSetRequest(HandleRejectedUplinkFrameSetRequest other) : this() {
      frameSet_ = other.frameSet_ != null ? other.frameSet_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HandleRejectedUplinkFrameSetRequest Clone() {
      return new HandleRejectedUplinkFrameSetRequest(this);
    }

    /// <summary>Field number for the "frame_set" field.</summary>
    public const int FrameSetFieldNumber = 1;
    private global::Chirpstack.Gateway.UplinkFrameSet frameSet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chirpstack.Gateway.UplinkFrameSet FrameSet {
      get { return frameSet_; }
      set {
        frameSet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HandleRejectedUplinkFrameSetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HandleRejectedUplinkFrameSetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FrameSet, other.FrameSet)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (frameSet_ != null) hash ^= FrameSet.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (frameSet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FrameSet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (frameSet_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FrameSet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (frameSet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FrameSet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HandleRejectedUplinkFrameSetRequest other) {
      if (other == null) {
        return;
      }
      if (other.frameSet_ != null) {
        if (frameSet_ == null) {
          FrameSet = new global::Chirpstack.Gateway.UplinkFrameSet();
        }
        FrameSet.MergeFrom(other.FrameSet);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (frameSet_ == null) {
              FrameSet = new global::Chirpstack.Gateway.UplinkFrameSet();
            }
            input.ReadMessage(FrameSet);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (frameSet_ == null) {
              FrameSet = new global::Chirpstack.Gateway.UplinkFrameSet();
            }
            input.ReadMessage(FrameSet);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
