"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import chirpstack_api.common.common_pb2
import chirpstack_api.gw.gw_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ResolveResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCATION_FIELD_NUMBER: builtins.int
    # Resolved location.
    @property
    def location(self) -> chirpstack_api.common.common_pb2.Location: ...
    def __init__(self,
        *,
        location : typing.Optional[chirpstack_api.common.common_pb2.Location] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"location",b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"location",b"location"]) -> None: ...
global___ResolveResult = ResolveResult

class FrameRXInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RX_INFO_FIELD_NUMBER: builtins.int
    # Uplink Gateway meta-data.
    @property
    def rx_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[chirpstack_api.gw.gw_pb2.UplinkRXInfo]: ...
    def __init__(self,
        *,
        rx_info : typing.Optional[typing.Iterable[chirpstack_api.gw.gw_pb2.UplinkRXInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"rx_info",b"rx_info"]) -> None: ...
global___FrameRXInfo = FrameRXInfo

class ResolveTDOARequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEV_EUI_FIELD_NUMBER: builtins.int
    FRAME_RX_INFO_FIELD_NUMBER: builtins.int
    DEVICE_REFERENCE_ALTITUDE_FIELD_NUMBER: builtins.int
    # Device ID.
    dev_eui: builtins.bytes = ...
    # Frame meta-data.
    @property
    def frame_rx_info(self) -> global___FrameRXInfo: ...
    # Device reference altitude.
    device_reference_altitude: builtins.float = ...
    def __init__(self,
        *,
        dev_eui : builtins.bytes = ...,
        frame_rx_info : typing.Optional[global___FrameRXInfo] = ...,
        device_reference_altitude : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"frame_rx_info",b"frame_rx_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dev_eui",b"dev_eui",u"device_reference_altitude",b"device_reference_altitude",u"frame_rx_info",b"frame_rx_info"]) -> None: ...
global___ResolveTDOARequest = ResolveTDOARequest

class ResolveMultiFrameTDOARequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DEV_EUI_FIELD_NUMBER: builtins.int
    FRAME_RX_INFO_SET_FIELD_NUMBER: builtins.int
    DEVICE_REFERENCE_ALTITUDE_FIELD_NUMBER: builtins.int
    # Device ID.
    dev_eui: builtins.bytes = ...
    # Frames meta-data.
    @property
    def frame_rx_info_set(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FrameRXInfo]: ...
    # Device reference altitude.
    device_reference_altitude: builtins.float = ...
    def __init__(self,
        *,
        dev_eui : builtins.bytes = ...,
        frame_rx_info_set : typing.Optional[typing.Iterable[global___FrameRXInfo]] = ...,
        device_reference_altitude : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dev_eui",b"dev_eui",u"device_reference_altitude",b"device_reference_altitude",u"frame_rx_info_set",b"frame_rx_info_set"]) -> None: ...
global___ResolveMultiFrameTDOARequest = ResolveMultiFrameTDOARequest

class ResolveTDOAResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESULT_FIELD_NUMBER: builtins.int
    # Resolve result.
    @property
    def result(self) -> global___ResolveResult: ...
    def __init__(self,
        *,
        result : typing.Optional[global___ResolveResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"result",b"result"]) -> None: ...
global___ResolveTDOAResponse = ResolveTDOAResponse

class ResolveMultiFrameTDOAResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESULT_FIELD_NUMBER: builtins.int
    # Resolve result.
    @property
    def result(self) -> global___ResolveResult: ...
    def __init__(self,
        *,
        result : typing.Optional[global___ResolveResult] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"result",b"result"]) -> None: ...
global___ResolveMultiFrameTDOAResponse = ResolveMultiFrameTDOAResponse
